#ifndef LIGHT_TREE_LEARNING_LAYOUT_H
#define LIGHT_TREE_LEARNING_LAYOUT_H
#define LT_FLAG_SG 0x400u
#define LT_FLAG_LEARNING 0x80000u
#define LT_RESET_BIT 2u
#define LT_CELL_CAPACITY 16384u
#define LT_CUT_MAX 32u
#define LT_CUT_INITIAL 4u
#define LT_CELL_HEADER 128u
#define LT_CLUSTER_BYTES 64u
#define LT_CELL_BYTES (LT_CELL_HEADER + LT_CUT_MAX * LT_CLUSTER_BYTES)
#define LT_LEARNING_BYTES (LT_CELL_CAPACITY * LT_CELL_BYTES)
#define LT_LEARNING_GROUPS (LT_CELL_CAPACITY / 64u)
#ifdef __cplusplus
static_assert((LT_CELL_CAPACITY & (LT_CELL_CAPACITY-1u))==0u);
#endif
#endif
