#pragma once
#define LT_FLAG_LEARNING 0x80000u
#define LT_RESET_BIT 2u
#define LT_INITIALIZE_BIT 4u

#define LT_REVALIDATE_BIT 8u
#define LT_FLAG_DEBUG 0x400u

#define LT_GRID_CAPACITY 65536u
#define LT_BLEND_FEEDBACK 1

#define LT_SURFACE_FILTER 1
#define LT_GLOBAL_CELLS 6u
#define LT_CELL_CAPACITY (LT_GRID_CAPACITY + LT_GLOBAL_CELLS)
#define LT_BUCKET_SIZE 4u
#define LT_CELL_PROBES (2u * LT_BUCKET_SIZE)
#define LT_CELL_HISTORY_MS 10000u
#define LT_CELL_DISTANT_MS 250u
#define LT_CELL_PRESSURE_MS 250u
#define LT_LEARNING_ALPHA_MIN (1.0f / 32.0f)
#define LT_MOMENT_HISTORY 4096u
#define LT_SAMPLE_HISTORY 8192u
#define LT_PRIOR_HISTORY 64u
#define LT_PARENT_FEEDBACK_RATE 32u
#define LT_LOD_WARMUP_START 0.5f
#define LT_LOD_BLEND_START 0.75f
#define LT_MAX_LEVEL 24u
#define LT_PARENT_LEVELS 4u
#define LT_KEY_BYTES 16u
#define LT_CUT_MAX 32u
#define LT_CUT_INITIAL 4u
#define LT_CELL_HEADER 128u

#define LT_FROZEN_BYTES 32u
#define LT_STATS_BYTES 32u
#define LT_CLUSTER_BYTES (LT_FROZEN_BYTES + LT_STATS_BYTES)
#define LT_FZ_NODE 0u
#define LT_FZ_BLAS 4u
#define LT_FZ_TRAIL 8u
#define LT_FZ_DEPTH 16u
#define LT_FZ_PARENT 20u
#define LT_FZ_PROBABILITY 24u
#define LT_FZ_CDF 28u
#define LT_ST_Q 0u
#define LT_ST_MEAN 4u
#define LT_ST_M2 8u
#define LT_ST_VISITS 12u
#define LT_ST_SELECTED 16u
#define LT_ST_POWER 20u
#define LT_CELL_BYTES (LT_KEY_BYTES + LT_CELL_HEADER + LT_CUT_MAX * LT_CLUSTER_BYTES)

#define LT_ACCUMULATOR_WORDS 5u
#define LT_ACCUMULATOR_BYTES (LT_ACCUMULATOR_WORDS * 8u)
#define LT_BATCH_BYTES (2u * LT_ACCUMULATOR_BYTES)
#define LT_LEARNING_BYTES (LT_CELL_CAPACITY * (LT_CELL_BYTES + LT_CUT_MAX * LT_BATCH_BYTES))
#define LT_LEARNING_GROUPS ((LT_CELL_CAPACITY + 63u) / 64u)
#ifdef __cplusplus
static_assert((LT_GRID_CAPACITY & (LT_GRID_CAPACITY-1u))==0u);
#endif
