#pragma once

// Cache offsets are shared by all SHaRC passes.
#define SHARC_CAPACITY (1u << 20u)
#define SHARC_ENTRY_BYTES 160u
#define SHARC_BUCKET_SIZE 16u
#define SHARC_STATE_BYTES (SHARC_CAPACITY * 4u)
#define SHARC_CACHE_BYTES (SHARC_STATE_BYTES + SHARC_CAPACITY * SHARC_ENTRY_BYTES)

#define GUIDE_CAPACITY (1u << 17u)
#define GUIDE_ENTRY_BYTES 576u
#define GUIDE_SLOTS 8u
#define GUIDE_STATE_BYTES (GUIDE_CAPACITY * 4u)
#define GUIDE_DIRTY_WORDS (GUIDE_CAPACITY / 32u)
#define GUIDE_DIRTY_OFFSET (SHARC_CACHE_BYTES + GUIDE_STATE_BYTES + GUIDE_CAPACITY * GUIDE_ENTRY_BYTES)
#define GUIDE_BYTES (GUIDE_STATE_BYTES + GUIDE_CAPACITY * GUIDE_ENTRY_BYTES + GUIDE_DIRTY_WORDS * 4u)

#define SHARC_DIRTY_OFFSET (SHARC_CACHE_BYTES + GUIDE_BYTES)
#define SHARC_DIRTY_WORDS (SHARC_CAPACITY / 32u)

#define LITE_REUSE_SIZE0 254u
#define LITE_REUSE_SIZE1 230u
#define LITE_REUSE_SIZE2 210u
#define LITE_REUSE_OFFSET (SHARC_DIRTY_OFFSET + SHARC_DIRTY_WORDS * 4u)
#define LITE_REUSE_TEXELS (LITE_REUSE_SIZE0 * LITE_REUSE_SIZE0 + \
    LITE_REUSE_SIZE1 * LITE_REUSE_SIZE1 + LITE_REUSE_SIZE2 * LITE_REUSE_SIZE2)
#include "LightTreeLearningLayout.h"
#define LT_BUFFER_OFFSET (LITE_REUSE_OFFSET + LITE_REUSE_TEXELS * 4u)
#define SHARC_BUFFER_BYTES (LT_BUFFER_OFFSET + LT_LEARNING_BYTES)

#define LITE_FLAG_ENABLED 0x1u
#define LITE_FLAG_SPATIAL 0x20u
#define LITE_FLAG_UNSHADOWED 0x8000u
#define LITE_FLAG_DEBUG 0x10000u

#define LITE_REUSE_FLAGS_SHIFT 16u
#define LITE_RESERVOIR_BYTES 32u
#define LITE_SLOTS_MAX 3u
#define SHARC_MAX_LEVEL 24u
#define SHARC_GROUP_SIZE 256u
#define SHARC_RESOLVE_GROUPS (SHARC_CAPACITY / SHARC_GROUP_SIZE)
#define SHARC_ROOT_CONSTANTS 37u

#define SHARC_DEBUG_MODE_SHIFT 1u
#define SHARC_DEBUG_MODE_MASK 3u
#define SHARC_DEBUG_CELLS 1u
#define SHARC_DEBUG_LIGHTING 2u
#define SHARC_DEBUG_GUIDING 3u
#define SHARC_DEBUG_OTHER_LEVEL_BIT 8u
#define SHARC_DEBUG_SCRATCH 12u

#define GUIDE_PARAM_ENABLED 1u
#define GUIDE_PARAM_QMAX_SHIFT 1u
#define GUIDE_PARAM_LEVEL_SHIFT 9u
#define GUIDE_PARAM_FRESHNESS_SHIFT 12u
#define GUIDE_PARAM_TRAIN (1u << 20u)

#define GUIDE_PARAM_REGULARIZE_SHIFT 22u
#define GUIDE_PARAM_DEPTH_SHIFT 28u
#ifdef __cplusplus
static_assert((SHARC_CAPACITY & (SHARC_CAPACITY - 1u)) == 0u);
static_assert(SHARC_CAPACITY % SHARC_BUCKET_SIZE == 0u);
static_assert(SHARC_BUCKET_SIZE <= 32u, "bucket occupancy masks are one word");
static_assert(SHARC_CAPACITY % SHARC_GROUP_SIZE == 0u);
static_assert(SHARC_DIRTY_WORDS % SHARC_GROUP_SIZE == 0u);
static_assert((GUIDE_CAPACITY & (GUIDE_CAPACITY - 1u)) == 0u);
static_assert(GUIDE_CAPACITY % SHARC_BUCKET_SIZE == 0u);
static_assert(GUIDE_CAPACITY <= SHARC_CAPACITY);
static_assert(SHARC_ROOT_CONSTANTS + 7u <= 64u);
#endif
