#ifndef CUMULUS_LAYOUT_H
#define CUMULUS_LAYOUT_H
#define CUMULUS_NOISE_SIZE 256u
#define CUMULUS_LIGHT_XZ 128u
#define CUMULUS_LIGHT_Y 32u
#define CUMULUS_LIGHT_SPAN_KM 48.0f
#define CUMULUS_ENV_W 512u
#define CUMULUS_ENV_H 256u
#define CUMULUS_AMBIENT_W 128u
#define CUMULUS_AMBIENT_H 16u
#define CUMULUS_QUERY_BYTES 64u
#define CUMULUS_NORMAL_SLOT 13u
#define CUMULUS_DEPTH_SLOT 14u
#endif
