"""Export a Scene to a Wavefront OBJ + (PBR-extended) MTL file set.

OBJ has no node graph or instance support, so transforms are baked into
vertex data and instances are expanded into separate `o` blocks. The
companion `.mtl` file uses the widely-supported PBR extension fields:

    Pr  - roughness factor                     map_Pr  - roughness texture
    Pm  - metallic factor                      map_Pm  - metallic texture
    Pc  - clearcoat factor                     map_Pc  - clearcoat texture
    Pcr - clearcoat roughness factor
    Ps  - sheen factor
    Ke  - emissive color                       map_Ke  - emissive texture
    Kd  - base/diffuse color                   map_Kd  - base color texture
    norm - tangent-space normal map (also map_bump for legacy readers)

PBRT-style roughness (α / GGX) is converted to perceptual (sqrt) on
write so values look right in the standard OBJ-PBR readers; Mitsuba
`principled` roughness is treated as already perceptual and passed
through.
"""

import math
import shutil
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from pbrt_parser import Param
from pbrt_scene import Material, Scene, ShapeEntry
from gltf_export import (
    _first_str,
    _mesh_from_objmesh,
    _mesh_from_plymesh,
    _mesh_from_sphere,
    _mesh_from_trianglemesh,
)


def _opt_float(params: Dict[str, Param], name: str) -> Optional[float]:
    p = params.get(name)
    if p is None or not p.values:
        return None
    v = p.values[0]
    if isinstance(v, str):
        return None
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def _is_textured(params: Dict[str, Param], name: str) -> Optional[str]:
    """If `params[name]` references a texture, return its name; else None."""
    p = params.get(name)
    if p is None or not p.values:
        return None
    if p.type == "texture":
        v = p.values[0]
        return v if isinstance(v, str) else None
    if not p.type and isinstance(p.values[0], str):
        return p.values[0]
    return None


class OBJExporter:
    def __init__(self, scene: Scene, out_dir: Path, basename: str):
        self.scene = scene
        self.out_dir = Path(out_dir)
        self.basename = basename

        self.obj: List[str] = []
        self.mtl: List[str] = []

        # Texture file copies: source-on-disk -> destination-in-output
        self._copies: Dict[Path, Path] = {}
        # Sqrt-transcoded roughness PNGs, keyed by (source, sqrt_alpha)
        self._rough_outputs: Dict[Tuple[str, bool], Path] = {}
        # MaterialKey -> emitted material name
        self._mat_names: Dict[int, str] = {}
        # Track names already written to avoid clashes
        self._used_mat_names: set = set()

        # OBJ index running totals (1-based)
        self._next_v = 1
        self._next_vn = 1
        self._next_vt = 1
        self._shape_counter = 0

    # ---- top-level ------------------------------------------------------

    def export(self):
        self.out_dir.mkdir(parents=True, exist_ok=True)
        self.obj.append(f"# Generated by pbrt2glb (OBJ exporter)")
        self.obj.append(f"mtllib {self.basename}.mtl")
        self.obj.append("")

        # Camera and lights are NOT representable in OBJ; emit a comment.
        if self.scene.camera is not None:
            self.obj.append("# (camera info dropped: OBJ has no camera concept)")
        if self.scene.lights:
            self.obj.append(f"# (dropped {len(self.scene.lights)} non-area lights)")
        self.obj.append("")

        for shape in self.scene.shapes:
            if shape.kind == "instance":
                template = self.scene.objects.get(shape.instance_name, [])
                for sub in template:
                    if sub.kind != "shape":
                        continue
                    composed = shape.ctm @ sub.ctm
                    self._emit_shape(sub, composed)
            else:
                self._emit_shape(shape, shape.ctm)

        # Write files
        obj_path = self.out_dir / f"{self.basename}.obj"
        mtl_path = self.out_dir / f"{self.basename}.mtl"
        obj_path.write_text("\n".join(self.obj) + "\n", encoding="utf-8")
        mtl_path.write_text("\n".join(self.mtl) + "\n", encoding="utf-8")
        return obj_path

    # ---- mesh emission --------------------------------------------------

    def _extract_mesh(self, shape: ShapeEntry):
        st = (shape.shape_type or "").lower()
        if st == "trianglemesh":
            return _mesh_from_trianglemesh(shape.shape_params)
        if st == "plymesh":
            return _mesh_from_plymesh(shape.shape_params, self.scene.base_dir)
        if st == "objmesh":
            return _mesh_from_objmesh(shape.shape_params, self.scene.base_dir)
        if st == "sphere":
            return _mesh_from_sphere(shape.shape_params)
        return None

    def _emit_shape(self, shape: ShapeEntry, ctm: np.ndarray):
        mesh = self._extract_mesh(shape)
        if mesh is None:
            return
        positions, indices, normals, uvs = mesh
        if positions is None or indices is None or len(positions) == 0:
            return

        n = len(positions)
        pos_h = np.concatenate(
            [positions, np.ones((n, 1), dtype=np.float32)], axis=1)
        pos_world = (ctm @ pos_h.T).T[:, :3].astype(np.float32)

        norm_world = None
        if normals is not None and len(normals) == n:
            try:
                nm = np.linalg.inv(ctm[:3, :3]).T
            except np.linalg.LinAlgError:
                nm = np.eye(3)
            nw = (nm @ normals.T).T.astype(np.float32)
            lens = np.linalg.norm(nw, axis=1, keepdims=True)
            lens[lens == 0] = 1.0
            norm_world = nw / lens

        if shape.reverse_orientation:
            indices = np.array(indices, dtype=np.uint32)[:, ::-1].copy()
            if norm_world is not None:
                norm_world = -norm_world

        mat_name = self._emit_material(
            shape.material, shape.area_light, shape.shape_params)

        self._shape_counter += 1
        obj_name = f"{mat_name}_{self._shape_counter}"
        self.obj.append(f"o {obj_name}")
        self.obj.append(f"usemtl {mat_name}")

        for px, py, pz in pos_world:
            self.obj.append(f"v {px:.6f} {py:.6f} {pz:.6f}")
        if norm_world is not None:
            for nx, ny, nz in norm_world:
                self.obj.append(f"vn {nx:.6f} {ny:.6f} {nz:.6f}")
        if uvs is not None:
            for u, v in uvs:
                self.obj.append(f"vt {u:.6f} {v:.6f}")

        v_off = self._next_v
        n_off = self._next_vn if norm_world is not None else 0
        t_off = self._next_vt if uvs is not None else 0
        has_n = norm_world is not None
        has_t = uvs is not None

        for tri in np.asarray(indices, dtype=np.uint32):
            a, b, c = int(tri[0]), int(tri[1]), int(tri[2])
            self.obj.append("f " + " ".join(
                self._fmt_ref(i, v_off, t_off, n_off, has_t, has_n)
                for i in (a, b, c)))

        self._next_v += n
        if has_n:
            self._next_vn += n
        if has_t:
            self._next_vt += n
        self.obj.append("")

    @staticmethod
    def _fmt_ref(i, v_off, t_off, n_off, has_t, has_n):
        v = i + v_off
        if has_t and has_n:
            return f"{v}/{i + t_off}/{i + n_off}"
        if has_n:
            return f"{v}//{i + n_off}"
        if has_t:
            return f"{v}/{i + t_off}"
        return f"{v}"

    # ---- material emission ----------------------------------------------

    def _allocate_mat_name(self, base: str) -> str:
        name = base or "mat"
        if name not in self._used_mat_names:
            self._used_mat_names.add(name)
            return name
        i = 2
        while f"{name}_{i}" in self._used_mat_names:
            i += 1
        new = f"{name}_{i}"
        self._used_mat_names.add(new)
        return new

    def _emit_material(self, mat: Optional[Material], area_light,
                       shape_params: Optional[Dict[str, Param]] = None) -> str:
        # Cache key spans the material identity, area-light tuple, and the
        # shape-level alpha source -- two shapes sharing a Material but
        # carrying different alpha cutout textures must emit distinct MTL
        # entries.
        cache_key = id(mat) if mat is not None else 0
        alpha_repr = self._alpha_repr(
            shape_params, mat.params if mat is not None else None)
        cache_key = hash((cache_key,
                          repr(area_light) if area_light else None,
                          alpha_repr))
        if cache_key in self._mat_names:
            return self._mat_names[cache_key]

        base_name = (mat.name if mat and mat.name
                     else f"mat_{len(self._mat_names) + 1}")
        name = self._allocate_mat_name(base_name)
        self._mat_names[cache_key] = name

        self.mtl.append(f"newmtl {name}")
        self.mtl.append("Ka 0.0 0.0 0.0")
        self.mtl.append("Ks 0.0 0.0 0.0")

        if mat is None:
            self.mtl.append("Kd 0.8 0.8 0.8")
            self.mtl.append("Pm 0.0")
            self.mtl.append("Pr 1.0")
        else:
            kind = (mat.kind or "diffuse").lower()
            params = mat.params

            if kind == "diffuse":
                self._mtl_color("Kd", "map_Kd", params, "reflectance",
                                default=(0.5, 0.5, 0.5))
                self.mtl.append("Pm 0.0")
                self.mtl.append("Pr 1.0")

            elif kind in ("coateddiffuse",):
                self._mtl_color("Kd", "map_Kd", params, "reflectance",
                                default=(0.5, 0.5, 0.5))
                self.mtl.append("Pm 0.0")
                self._mtl_float("Pr", "map_Pr", params, "roughness",
                                default=0.5, sqrt_alpha=True)

            elif kind in ("conductor", "coatedconductor"):
                self._mtl_color("Kd", "map_Kd", params, "reflectance",
                                default=(1.0, 1.0, 1.0))
                self.mtl.append("Pm 1.0")
                self._mtl_float("Pr", "map_Pr", params, "roughness",
                                default=0.0, sqrt_alpha=True)

            elif kind in ("dielectric", "thindielectric"):
                self.mtl.append("Kd 1.0 1.0 1.0")
                self.mtl.append("Pm 0.0")
                self._mtl_float("Pr", "map_Pr", params, "roughness",
                                default=0.0, sqrt_alpha=True)
                self.mtl.append("Tr 0.95")
                self.mtl.append("d 0.05")
                ior = _opt_float(params, "eta") or _opt_float(params, "ior")
                if ior is not None:
                    self.mtl.append(f"Ni {ior:.4f}")

            elif kind in ("principled", "principledthin"):
                # Mitsuba `principled` roughness is already perceptual,
                # so we pass it through (sqrt_alpha=False).
                self._mtl_color("Kd", "map_Kd", params, "reflectance",
                                default=(0.5, 0.5, 0.5))
                self._mtl_float("Pm", "map_Pm", params, "metallic",
                                default=0.0, sqrt_alpha=False)
                self._mtl_float("Pr", "map_Pr", params, "roughness",
                                default=0.5, sqrt_alpha=False)

            else:  # subsurface, measured, interface, unknown
                self._mtl_color("Kd", "map_Kd", params, "reflectance",
                                default=(0.7, 0.7, 0.7))
                self.mtl.append("Pm 0.0")
                self.mtl.append("Pr 0.5")

            # Normal map (file path or texture ref)
            self._maybe_emit_normal_map(params)

            # Alpha cutout / opacity (PBRT shape-level `alpha` or Mitsuba
            # mask wrapper's `_opacity`). The renderer's MTL loader reads
            # `d`/`map_d` for the channel and a custom `alpha_cutoff` key
            # for the threshold (ObjLoader.h:857).
            self._maybe_emit_alpha(params, shape_params)

        # Emissive color (from area light)
        if area_light is not None:
            _, lp = area_light
            L = lp.get("L")
            if L is not None and L.values:
                vals = [v for v in L.values if not isinstance(v, str)]
                if len(vals) >= 3:
                    m = max(1.0, max(vals))
                    self.mtl.append(
                        f"Ke {vals[0] / m:.4f} {vals[1] / m:.4f} {vals[2] / m:.4f}")
                elif len(vals) == 1:
                    self.mtl.append(
                        f"Ke {vals[0]:.4f} {vals[0]:.4f} {vals[0]:.4f}")

        self.mtl.append("illum 2")
        self.mtl.append("")
        return name

    # ---- material helpers -----------------------------------------------

    def _mtl_color(self, factor_key: str, tex_key: str,
                   params: Dict[str, Param], name: str,
                   default=(1.0, 1.0, 1.0)):
        p = params.get(name)
        tex_name = _is_textured(params, name)
        if tex_name is not None:
            rel = self._resolve_named_texture(tex_name)
            if rel is not None:
                self.mtl.append(f"{factor_key} 1.0000 1.0000 1.0000")
                self.mtl.append(f"{tex_key} {rel}")
                return
        if p is not None and p.values:
            vals = [v for v in p.values if not isinstance(v, str)]
            if len(vals) >= 3:
                self.mtl.append(
                    f"{factor_key} {vals[0]:.4f} {vals[1]:.4f} {vals[2]:.4f}")
                return
            if len(vals) == 1:
                v = vals[0]
                self.mtl.append(f"{factor_key} {v:.4f} {v:.4f} {v:.4f}")
                return
        self.mtl.append(
            f"{factor_key} {default[0]:.4f} {default[1]:.4f} {default[2]:.4f}")

    def _mtl_float(self, factor_key: str, tex_key: str,
                   params: Dict[str, Param], name: str,
                   default: float = 0.0, sqrt_alpha: bool = False):
        tex_name = _is_textured(params, name)
        if tex_name is not None:
            rel = self._resolve_named_texture(
                tex_name, sqrt_alpha=sqrt_alpha, force_grayscale=True)
            if rel is not None:
                self.mtl.append(f"{factor_key} 1.0000")
                self.mtl.append(f"{tex_key} {rel}")
                return
        v = _opt_float(params, name)
        if v is None:
            v = default
        if sqrt_alpha:
            v = math.sqrt(max(0.0, v))
        self.mtl.append(f"{factor_key} {v:.4f}")

    @staticmethod
    def _alpha_repr(shape_params: Optional[Dict[str, Param]],
                    mat_params: Optional[Dict[str, Param]]):
        """Stable cache-key fragment for the alpha source on a shape."""
        for src, key in ((shape_params, "alpha"), (mat_params, "_opacity")):
            if not src:
                continue
            p = src.get(key)
            if p is None or not p.values:
                continue
            return (key, p.type, tuple(p.values))
        return None

    def _maybe_emit_alpha(self, mat_params: Dict[str, Param],
                          shape_params: Optional[Dict[str, Param]]):
        """Write `d`, `map_d`, and the renderer's `alpha_cutoff` MTL key
        when an alpha source is present. PBRT shape-level `alpha` wins
        over Mitsuba mask `_opacity`."""
        for src, key in ((shape_params, "alpha"), (mat_params, "_opacity")):
            if not src:
                continue
            p = src.get(key)
            if p is None or not p.values:
                continue
            v = p.values[0]
            if isinstance(v, str):
                rel = self._resolve_named_texture(v)
                if rel is not None:
                    self.mtl.append(f"map_d {rel}")
                    self.mtl.append("alpha_cutoff 0.5")
                return
            try:
                a = float(v)
            except (TypeError, ValueError):
                return
            a = max(0.0, min(1.0, a))
            if a < 0.999:
                self.mtl.append(f"d {a:.4f}")
            return

    def _maybe_emit_normal_map(self, params: Dict[str, Param]):
        nm = params.get("normalmap")
        if nm is None or not nm.values:
            return
        v = nm.values[0]
        if not isinstance(v, str):
            return
        if nm.type == "texture":
            rel = self._resolve_named_texture(v)
        else:
            src = (self.scene.base_dir / v).resolve()
            rel = self._copy_texture(src)
        if rel is not None:
            # 'norm' is the modern OBJ-PBR spelling; 'map_bump' is older.
            self.mtl.append(f"norm {rel}")
            self.mtl.append(f"map_bump {rel}")

    # ---- texture file management ---------------------------------------

    def _resolve_named_texture(self, tex_name: str,
                               sqrt_alpha: bool = False,
                               force_grayscale: bool = False
                               ) -> Optional[str]:
        tdef = self.scene.textures.get(tex_name)
        if tdef is None or tdef.tclass.lower() != "imagemap":
            return None
        fname = _first_str(tdef.params.get("filename"))
        if not fname:
            return None
        src = (self.scene.base_dir / fname).resolve()
        if sqrt_alpha:
            return self._sqrt_transcoded(src)
        return self._copy_texture(src)

    def _copy_texture(self, src: Path) -> Optional[str]:
        if src in self._copies:
            return self._copies[src].relative_to(self.out_dir).as_posix()
        if not src.exists():
            print(f"  warning: texture not found: {src}")
            return None
        tex_dir = self.out_dir / "textures"
        tex_dir.mkdir(parents=True, exist_ok=True)
        candidate = tex_dir / src.name
        i = 1
        while candidate.exists() and not _same_file(candidate, src):
            candidate = tex_dir / f"{src.stem}_{i}{src.suffix}"
            i += 1
        try:
            shutil.copy2(src, candidate)
        except Exception as e:
            print(f"  warning: could not copy texture {src}: {e}")
            return None
        self._copies[src] = candidate
        return candidate.relative_to(self.out_dir).as_posix()

    def _sqrt_transcoded(self, src: Path) -> Optional[str]:
        """Write a perceptual-roughness PNG (sqrt of source α) and return
        its relative path. Caches by source path."""
        key = (str(src), True)
        if key in self._rough_outputs:
            return self._rough_outputs[key].relative_to(self.out_dir).as_posix()
        if not src.exists():
            print(f"  warning: roughness texture not found: {src}")
            return None
        try:
            from PIL import Image as PILImage
            with PILImage.open(src) as im:
                im.load()
                gray = im.convert("L")
                arr = np.asarray(gray, dtype=np.uint8)
        except Exception as e:
            print(f"  warning: could not transcode roughness {src}: {e}")
            return self._copy_texture(src)

        a_norm = arr.astype(np.float32) / 255.0
        a_norm = np.sqrt(a_norm)
        out_arr = np.clip(a_norm * 255.0 + 0.5, 0, 255).astype(np.uint8)

        tex_dir = self.out_dir / "textures"
        tex_dir.mkdir(parents=True, exist_ok=True)
        candidate = tex_dir / f"{src.stem}_perceptual.png"
        i = 1
        while candidate.exists():
            candidate = tex_dir / f"{src.stem}_perceptual_{i}.png"
            i += 1
        try:
            from PIL import Image as PILImage
            PILImage.fromarray(out_arr, mode="L").save(candidate, format="PNG")
        except Exception as e:
            print(f"  warning: could not write transcoded roughness {candidate}: {e}")
            return self._copy_texture(src)
        self._rough_outputs[key] = candidate
        return candidate.relative_to(self.out_dir).as_posix()


def _same_file(a: Path, b: Path) -> bool:
    try:
        return a.resolve() == b.resolve() or a.samefile(b)
    except OSError:
        return False


def export_to_obj(scene: Scene, out_dir, basename: str):
    OBJExporter(scene, Path(out_dir), basename).export()
